# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - webscraperquart

on:
    push:
        branches:
        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Python version
                uses: actions/setup-python@v1
                with:
                    python-version: '3.12'

            -   name: Install and configure poetry
                uses: snok/install-poetry@v1
                with:
                    version: 1.8.2
                    virtualenvs-create: true
                    virtualenvs-in-project: true

            -   name: Load cached venv
                uses: actions/cache@v3
                id: cache-poetry-dependencies
                with:
                    path: .venv
                    key: ${{ runner.os }}-3.12-${{ hashFiles('**/poetry.lock') }}

            -   name: Install dependencies
                if: steps.cache-poetry-dependencies.outputs.cache-hit != 'true'
                run: poetry install --no-interaction --no-root

            -   name: Run tests
                run: |
                    cd /home/runner/work/webscraperquart/webscraperquart
                    poetry run test

            -   name: Zip artifact for deployment
                run: zip release.zip ./* -r

            -   name: Upload artifact for deployment jobs
                uses: actions/upload-artifact@v3
                with:
                    name: python-app
                    path: |
                        release.zip
                        !venv/

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            -   name: Download artifact from build job
                uses: actions/download-artifact@v3
                with:
                    name: python-app

            -   name: Unzip artifact for deployment
                run: unzip release.zip

        
            -   name: Login to Azure
                uses: azure/login@v1
                with:
                    client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_448E28F163F94CF4935F2F6F34BF299E }}
                    tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E23884C00A8D466A8FAE2928572660D8 }}
                    subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C8CD8709DD040E9A5F4514FB3C1B5C3 }}

            -   name: 'Deploy to Azure Web App'
                uses: azure/webapps-deploy@v2
                id: deploy-to-webapp
                with:
                    app-name: 'webscraperquart'
                    slot-name: 'Production'
                    package: '.'
                    startup-command: 'poetry run prod'
